---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: networking
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowOriginList:
      - "https://${SECRET_DOMAIN}"
    accessControlMaxAge: 100
    addVaryHeader: true
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    stsIncludeSubdomains: false
    stsSeconds: 63072000
    hostsProxyHeaders:
      - "X-Forwarded-Host"
      - "Forwarded"
    customResponseHeaders:
      X-xss-protection: "1"
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
